from rest_framework import serializers
from .models import Job, MatchHistory

class JobSerializer(serializers.ModelSerializer):
    """🚀 Serializer for Neural Job Postings"""
    
    class Meta:
        model = Job
        fields = "__all__"
        read_only_fields = ["user", "created_at", "updated_at"]

    def validate_skills_required(self, value):
        """
        Validates the JSON list of skills generated by Llama 3 or entered by Admin.
        """
        if not isinstance(value, list) or len(value) == 0:
            raise serializers.ValidationError("Identify at least one required skill for this job.")
        
    
        return [skill.strip() for skill in value if isinstance(skill, str) and skill.strip()]


class MatchHistorySerializer(serializers.ModelSerializer):
    """📊 Serializer for Student Match Analytics with AI Insights"""
    
    job_title = serializers.CharField(source="job.title", read_only=True)
    company_name = serializers.CharField(source="job.company_name", read_only=True)
    job_source = serializers.CharField(source="job.source", read_only=True) 
    match_date = serializers.DateTimeField(source="created_at", format="%b %d, %Y", read_only=True)
    
    class Meta:
        model = MatchHistory
        fields = [
            "id", "user", "resume", "job", "job_title", 
            "company_name", "job_source", "matched_skills",
            "missing_skills", 
            "match_percentage", "ai_reason", "match_date"
        ]
        read_only_fields = ["user", "match_percentage", "matched_skills", "missing_skills", "ai_reason", "created_at"]