# Generated by Django 6.0.2 on 2026-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_apply_link_job_requirements_job_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='missing_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(default=list),
        ),
    ]
