# Generated by Django 6.0.2 on 2026-05-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_salary_range_matchhistory_explanation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchhistory',
            old_name='explanation',
            new_name='ai_reason',
        ),
    ]
