# Generated by Django 6.0.2 on 2026-02-18 09:04

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/', validators=[users.models.validate_pdf]),
        ),
    ]
