# Generated by Django 6.0.2 on 2026-03-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
