# Generated by Django 6.0.2 on 2026-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_securitylog_user_is_locked_user_last_attempt_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='Sargodha, Pakistan', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated skills for AI processing'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
