# Generated by Django 6.0.2 on 2026-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_resume_address_resume_education_resume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='student', help_text='Determines if the user sees Student or Admin dashboard features', max_length=10),
        ),
    ]
