# Generated by Django 6.0.2 on 2026-03-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('best_feature', models.CharField(max_length=100)),
                ('problems', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='status',
            field=models.CharField(default='FAILED', max_length=50),
        ),
    ]
