# Generated by Django 6.0.2 on 2026-05-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userfeedback_alter_securitylog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_skills',
            new_name='skills',
        ),
    ]
