# Generated by Django 6.0.2 on 2026-05-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_resume_skills_resume_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
